### ISSUE TITLE
Tasks that take longer than 15 minutes to render fail

### ISSUE THREAD

**Issue by leMaik** [ChunkyCloud/render-node#6]
```
[13:04:31  INFO]: [TaskWorker] New task: 24 spp for job ***
[13:04:32  INFO]: [TaskWorker] Downloading scene files...
[13:04:32  INFO]: [TaskWorker] Rendering...
Render dump not found: scene.dump
Render dump not found: scene.dump.backup
[13:19:32 ERROR]: [RenderWorker] An error occurred in the worker loop
com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - consumer ack timed out on channel 1, class-id=0, method-id=0)
	at com.rabbitmq.client.QueueingConsumer.handle(QueueingConsumer.java:202)
	at com.rabbitmq.client.QueueingConsumer.nextDelivery(QueueingConsumer.java:219)
	at de.lemaik.renderservice.renderer.rendering.RenderWorker.run(RenderWorker.java:102)
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - consumer ack timed out on channel 1, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.ChannelN.asyncShutdown(ChannelN.java:483)
	at com.rabbitmq.client.impl.ChannelN.processAsync(ChannelN.java:320)
	at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:143)
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:90)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:559)
	at java.lang.Thread.run(Thread.java:745)
```

There seems to be a 15 minute timeout if RabbitMQ that we should set to something higher: https://stackoverflow.com/a/67581599

**Comment by leMaik** [comment]
Obsolete in the upcoming version.
